### ISSUE TITLE
Path related error in import reconstruction

### ISSUE THREAD

**Issue by io7m** [io7m/kstructural#19]
```
$ pwd
/home/io7m/git/com.github/io7m/kstructural

$ java -jar io7m-kstructural-cmdline/target/io7m-kstructural-cmdline-0.1.0-main.jar convert -file io7m-kstructural-specification/src/main/resources/com/io7m/kstructural/specification/specification.sd -output-dir /tmp/export
ERROR com.io7m.kstructural.cmdline.KSCLMain: 'other' is different type of Path
java.lang.IllegalArgumentException: 'other' is different type of Path
	at sun.nio.fs.UnixPath.relativize(UnixPath.java:416) ~[na:1.8.0_92]
	at sun.nio.fs.UnixPath.relativize(UnixPath.java:43) ~[na:1.8.0_92]
	at com.io7m.kstructural.frontend.KSExporter.exportReconstructingImports(KSExporter.java:185) ~[io7m-kstructural-cmdline-0.1.0-main.jar:0.1.0]
	at com.io7m.kstructural.frontend.KSExporter.export(KSExporter.java:111) ~[io7m-kstructural-cmdline-0.1.0-main.jar:0.1.0]
	at com.io7m.kstructural.frontend.KSOpConvert.call(KSOpConvert.java:104) ~[io7m-kstructural-cmdline-0.1.0-main.jar:0.1.0]
	at com.io7m.kstructural.frontend.KSOpConvert.call(KSOpConvert.java:32) ~[io7m-kstructural-cmdline-0.1.0-main.jar:0.1.0]
	at com.io7m.kstructural.cmdline.KSCLMain$CommandConvert.call(KSCLMain.java:374) ~[io7m-kstructural-cmdline-0.1.0-main.jar:0.1.0]
	at com.io7m.kstructural.cmdline.KSCLMain$CommandConvert.call(KSCLMain.java:310) ~[io7m-kstructural-cmdline-0.1.0-main.jar:0.1.0]
	at com.io7m.kstructural.cmdline.KSCLMain.run(KSCLMain.java:121) [io7m-kstructural-cmdline-0.1.0-main.jar:0.1.0]
	at com.io7m.kstructural.cmdline.KSCLMain.main(KSCLMain.java:93) [io7m-kstructural-cmdline-0.1.0-main.jar:0.1.0]
```

**Comment by io7m** [comment]
The code inside the jre that triggers this is:

```
public UnixPath relativize(Path var1) {
    UnixPath var2 = toUnixPath(var1);
    if(var2.equals(this)) {
      return this.emptyPath();
    } else if(this.isAbsolute() != var2.isAbsolute()) {
      throw new IllegalArgumentException("\'other\' is different type of Path");
    } else if(this.isEmpty()) {
      return var2;
    } else {
```
