### ISSUE TITLE
XOM fails to escape 0x0

### ISSUE THREAD

**Issue by io7m** [io7m/kstructural#34]
Writing a document containing the null character `0x0` results in:

```
nu.xom.IllegalCharacterDataException: 0x0 is not allowed in XML content
	at nu.xom.Verifier.throwIllegalCharacterDataException(Unknown Source) ~[io7m-kstructural-cmdline-0.1.0-main.jar:0.1.0]
	at nu.xom.Verifier.checkPCDATA(Unknown Source) ~[io7m-kstructural-cmdline-0.1.0-main.jar:0.1.0]
	at nu.xom.Text._setValue(Unknown Source) ~[io7m-kstructural-cmdline-0.1.0-main.jar:0.1.0]
	at nu.xom.Text.<init>(Unknown Source) ~[io7m-kstructural-cmdline-0.1.0-main.jar:0.1.0]
	at nu.xom.Element.appendChild(Unknown Source) ~[io7m-kstructural-cmdline-0.1.0-main.jar:0.1.0]
	at com.io7m.kstructural.xom.KSXOM.inlineVerbatim(KSXOM.kt:456) ~[io7m-kstructural-cmdline-0.1.0-main.jar:0.1.0]
```

Nulls should be replaced with `U+FFFD`.

**Comment by io7m** [comment]
The problem here is that ranges of characters are outright not allowed to appear in XML documents, even when escaped with entities.

https://en.wikipedia.org/wiki/Valid_Characters_in_XML#XML_1.0

It's not clear _where_ this should be handled.

**Comment by io7m** [comment]
This was accidentally closed early: This has only been implemented for the XHTML XOM output and not the XML serializer.
